USE [master]
GO
/****** Object:  Database [AticaGestionUsuarios]    Script Date: 30/1/2026 21:21:25 ******/
CREATE DATABASE [AticaGestionUsuarios]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AticaGestionUsuarios', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\AticaGestionUsuarios.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AticaGestionUsuarios_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\AticaGestionUsuarios_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [AticaGestionUsuarios] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AticaGestionUsuarios].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AticaGestionUsuarios] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AticaGestionUsuarios] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AticaGestionUsuarios] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AticaGestionUsuarios] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AticaGestionUsuarios] SET ARITHABORT OFF 
GO
ALTER DATABASE [AticaGestionUsuarios] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [AticaGestionUsuarios] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AticaGestionUsuarios] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AticaGestionUsuarios] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AticaGestionUsuarios] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AticaGestionUsuarios] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AticaGestionUsuarios] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AticaGestionUsuarios] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AticaGestionUsuarios] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AticaGestionUsuarios] SET  ENABLE_BROKER 
GO
ALTER DATABASE [AticaGestionUsuarios] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AticaGestionUsuarios] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AticaGestionUsuarios] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AticaGestionUsuarios] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AticaGestionUsuarios] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AticaGestionUsuarios] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AticaGestionUsuarios] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AticaGestionUsuarios] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [AticaGestionUsuarios] SET  MULTI_USER 
GO
ALTER DATABASE [AticaGestionUsuarios] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AticaGestionUsuarios] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AticaGestionUsuarios] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AticaGestionUsuarios] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AticaGestionUsuarios] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AticaGestionUsuarios] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [AticaGestionUsuarios] SET QUERY_STORE = ON
GO
ALTER DATABASE [AticaGestionUsuarios] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [AticaGestionUsuarios]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 30/1/2026 21:21:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](100) NOT NULL,
	[apellido] [varchar](100) NOT NULL,
	[documento] [varchar](20) NOT NULL,
	[email] [varchar](150) NOT NULL,
	[rol] [varchar](20) NOT NULL,
	[username] [varchar](50) NOT NULL,
	[password_hash] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[documento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Usuarios]  WITH CHECK ADD CHECK  (([rol]='Usuario' OR [rol]='Administrador'))
GO
USE [master]
GO
ALTER DATABASE [AticaGestionUsuarios] SET  READ_WRITE 
GO
